services:
  nginx:
    image: nginx
    links:
      - sspanel
    volumes:
      - ./docker-nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker-site.conf:/etc/nginx/conf.d/default.conf:ro
      #      - ./data/sockets/php8.2-fpm.sock:/run/php/php8.2-fpm.sock:ro
      - ./:/var/www/html
      - ./certs:/etc/nginx/certs
    ports:
      - "8081:443"
    command: [ nginx, '-g', 'daemon off;' ]

  sspanel:
    build: .
    depends_on:
      - mariadb
    volumes:
      #      - ./data/sockets/php8.2-fpm.sock:/run/php/php8.2-fpm.sock
      - ./data/sockets/mariadb:/var/run/mysqld:ro
      - ./:/var/www/html

  mariadb:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: examplepasswordboom
      MYSQL_DATABASE: sspanel
      MYSQL_USER: sspanel
      MYSQL_PASSWORD: sspanel
    #    ports:  # use socket instead
    #      - "3306:3306"
    volumes:
      - ./data/sockets/mariadb:/var/run/mysqld
      - ./sql/glzjin_all.sql:/docker-entrypoint-initdb.d/init.sql:ro
    # note: db data is ephemeral (not persistent between docker compose)

  influxdb2:
    image: influxdb:2
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: sspanel
      DOCKER_INFLUXDB_INIT_PASSWORD: sspanel-pswd
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: bifrost-my-token
      DOCKER_INFLUXDB_INIT_ORG: bifrost-org
      DOCKER_INFLUXDB_INIT_BUCKET: bifrost-bucket

volumes:
  db:
  site:

networks:
  default:
    name: sspanel_network
    driver: bridge
